<a href="https://colab.research.google.com/github/DeviArya/Data-Science/blob/main/NUMPY_PRACTICE_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy basic Operators
1. np.arraay([1,2,3]) ---> 1D array
2. np.array([(1,2,3),(4,5,6)])--->2D array
3. np.arange(start,stop,step)---> range array

##Placeholders operation

1. np.linspace(0,2,9)-->add evenly spaced values b/w intervel to the array of length
2. np.zeros((1,2))
3. np.ones((1,2))
4. np.random.random((5,6))
5. np.empty((2,2))

##Array

1. array.shape
2. len(array)
3. array.ndim
4. array.dtype
5. array.astype(type)-->covert to datatpe
6. type(array)

##copying/sorting

1. np.copy(array)
2. array2=array.copy()
3. array.sort()
4. array.sort(axis=0)

#Array manipulation

##adding or removing elements

1. np.append(a,b)
2. np.insert(arrray,1,2,axis)
3. np.resize((2,4))
4. np.delete(array,1,axis)

##Combining arrays

1. np.concatenate((a,b),axis=0)
2. np.vstack((a,b))
3. np.hstack((a,b))

##Splitting array

numpy.split()
np.array_split(array,3)
numpy.hsplit(array,3)

##more

1. arr1=array.flattern()
2. arr=np.transpose(array1) or arr.T
3. inverse=np.linalg.iv=nv(arr)


#Mathematics
##Opertors
1. np.add(x,y)
2. np.substract(x,y)
3. np.divide(x,y)
4. np.multiply(x,y)
5. np.sqrt(x)
6. np.sin(x)
7. np.cos(x)
8. np.log(x)
9. np.dot(x,y)
10. np.root(1,0,-4)--> polinomial coefficients

## Comparison

1. ==,!=,<,>,<=,>=
2. np.array_equal(x,y)

##Basic stat

1. np.mean(arr)
2. np.median(arr)
3. npstd(arr)
4. array.corrcoef()

## More
1. array.sum()
2. array.min()
3. array.max(axis=0)
4. array.cumsum(axis=0)-->cumulative sum

1. Write a Numpy program to get the Numpy version and show the Numpy build configuration.

In [ ]:
# importing the Numpy library with an alias 'np'
import numpy as np

#printing the version of Numpy installed
print(np.__version__)

#printing the configuration details of Numpy
print(np.show_config())

1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

2. Write a NumPy program to get help with the add function.

In [ ]:
# importing numpy as np
import numpy as np

#printing inf about the np.add function by using np.info()
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

3. Write a NumPy program to test whether none of the elements of a given array are zero.

In [ ]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating a NumPy array 'x' containing elements 1, 2, 3, and 4
x = np.array([1, 2, 3, 4])

# Printing the original array 'x'
print("Original array:")
print(x)

# Checking if none of the elements in the array 'x' is zero and printing the result
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

# Reassigning array 'x' to a new array containing elements 0, 1, 2, and 3
x = np.array([0, 1, 2, 3])

# Printing the new array 'x'
print("Original array:")
print(x)

# Checking if none of the elements in the updated array 'x' is zero and printing the result
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


4. Write a NumPy program to test if any of the elements of a given array are non-zero.

In [ ]:
# Write a NumPy program to test if any of the elements of a given array are non-zero.

import numpy as np

# Create a NumPy array 'x' containing elements 1, 2, 3, and 4
x = np.array([1, 2, 3, 4])

# Print the original array 'x'
print("Original array:")
print(x)

# Check if any of the elements in the array 'x' are non-zero and print the result
print("Test if any of the elements of the said array are non-zero:")
print(np.any(x))

# Reassign array 'x' to a new array containing elements 0, 0, 0, and 0
x = np.array([0, 0, 0, 0])

# Print the new array 'x'
print("Original array:")
print(x)

# Check if any of the elements in the updated array 'x' are non-zero and print the result
print("Test if any of the elements of the said array are non-zero:")
print(np.any(x))


Original array:
[1 2 3 4]
Test if any of the elements of the said array are non-zero:
True
Original array:
[0 0 0 0]
Test if any of the elements of the said array are non-zero:
False


5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).

In [ ]:
#5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).

import numpy as np

# Create a NumPy array 'x' containing elements 1, 2, 3, and 4
x = np.array([1, 2, 3, 4])

# Print the original array 'x'
print("Original array:")
print(x)

# Test element-wise for finiteness (not infinity or not a number) and print the result
print("Test element-wise for finiteness:")
print(np.isfinite(x))

# Reassign array 'x' to a new array containing elements 1, 2, 3, and infinity
x = np.array([1, 2, 3, np.inf])

# Print the new array 'x'
print("Original array:")
print(x)

# Test element-wise for finiteness and print the result
print("Test element-wise for finiteness:")
print(np.isfinite(x))


Original array:
[1 2 3 4]
Test element-wise for finiteness:
[ True  True  True  True]
Original array:
[ 1.  2.  3. inf]
Test element-wise for finiteness:
[ True  True  True False]


6. Write a NumPy program to test elements-wise for positive or negative infinity.

In [ ]:
#6. Write a NumPy program to test elements-wise for positive or negative infinity.

import numpy as np

# Create a NumPy array 'x' containing elements 1, 2, 3, and infinity
x = np.array([1, 2, 3, np.inf])

# Print the original array 'x'
print("Original array:")
print(x)

# Test element-wise for positive infinity and print the result
print("Test element-wise for positive infinity:")
print(np.isposinf(x))

# Test element-wise for negative infinity and print the result
print("Test element-wise for negative infinity:")
print(np.isneginf(x))

# Reassign array 'x' to a new array containing elements 1, 2, 3, and -infinity
x = np.array([1, 2, 3, -np.inf])

# Print the new array 'x'
print("Original array:")
print(x)

# Test element-wise for positive infinity and print the result
print("Test element-wise for positive infinity:")
print(np.isposinf(x))

# Test element-wise for negative infinity and print the result
print("Test element-wise for negative infinity:")
print(np.isneginf(x))


Original array:
[ 1.  2.  3. inf]
Test element-wise for positive infinity:
[False False False  True]
Test element-wise for negative infinity:
[False False False False]
Original array:
[  1.   2.   3. -inf]
Test element-wise for positive infinity:
[False False False False]
Test element-wise for negative infinity:
[False False False  True]


7. Write a NumPy program to test element-wise for NaN of a given array.

In [ ]:
#7. Write a NumPy program to test element-wise for NaN of a given array.

# Import the NumPy library with an alias 'np'
import numpy as np

# Create a NumPy array 'x' containing elements 1, 2, 3, and NaN
x = np.array([1, 2, 3, np.nan])

# Print the original array 'x'
print("Original array:")
print(x)

# Test element-wise for NaN and print the result
print("Test element-wise for NaN:")
print(np.isnan(x))

# Reassign array 'x' to a new array containing elements 1, 2, 3, and infinity
x = np.array([1, 2, 3, np.inf])

# Print the new array 'x'
print("Original array:")
print(x)

# Test element-wise for NaN and print the result
print("Test element-wise for NaN:")
print(np.isnan(x))


Original array:
[ 1.  2.  3. nan]
Test element-wise for NaN:
[False False False  True]
Original array:
[ 1.  2.  3. inf]
Test element-wise for NaN:
[False False False False]


8. Write a NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not.

In [ ]:
#8. Write a NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not.

import numpy as np

# Create a NumPy array 'x' containing elements 1, 2, 3, and 4
x = np.array([1, 2, 3, 4])

# Print the original array 'x'
print("Original array:")
print(x)

# Test element-wise for complex numbers and print the result
print("Test element-wise for complex numbers:")
print(np.iscomplex(x))

# Test element-wise for real numbers and print the result
print("Test element-wise for real numbers:")
print(np.isreal(x))

# Test if the given number 1 is of a scalar type and print the result
print("Test if the given number 1 is of a scalar type:")
print(np.isscalar(1))

# Reassign array 'x' to a new array containing elements 1, 2, 3, and 4j
x = np.array([1, 2, 3, 4j])

# Print the new array 'x'
print("Original array:")
print(x)

# Test element-wise for complex numbers and print the result
print("Test element-wise for complex numbers:")
print(np.iscomplex(x))

# Test element-wise for real numbers and print the result
print("Test element-wise for real numbers:")
print(np.isreal(x))

# Test if the given number 1j is of a scalar type and print the result
print("Test if the given number 1j is of a scalar type:")
print(np.isscalar(1j))


Original array:
[1 2 3 4]
Test element-wise for complex numbers:
[False False False False]
Test element-wise for real numbers:
[ True  True  True  True]
Test if the given number 1 is of a scalar type:
True
Original array:
[1.+0.j 2.+0.j 3.+0.j 0.+4.j]
Test element-wise for complex numbers:
[False False False  True]
Test element-wise for real numbers:
[ True  True  True False]
Test if the given number 1j is of a scalar type:
True


9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [ ]:
# 9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

import numpy as np

# Create two NumPy arrays 'x' and 'y'
x = np.array([1, 2, 3, 4])
y = np.array([1.0001, 2.0002, 3.0003, 4.0004])

# Print the original arrays
print("Original arrays:")
print(x)
print(y)

# Test element-wise for equality within a tolerance of 0.0005 and print the result
print("Test element-wise for equality within a tolerance of 0.0005:")
print(np.allclose(x, y, atol=0.0005))

# Change the tolerance to 0.0004 and print the result
print("Test element-wise for equality within a tolerance of 0.0004:")
print(np.allclose(x, y, atol=0.0001))


Original arrays:
[1 2 3 4]
[1.0001 2.0002 3.0003 4.0004]
Test element-wise for equality within a tolerance of 0.0005:
True
Test element-wise for equality within a tolerance of 0.0004:
False


10. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [ ]:
#0. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

import numpy as np

# Create two NumPy arrays 'x' and 'y'
x = np.array([1, 2, 3, 4])
y = np.array([1, 2, 3, 5])

# Print the original arrays
print("Original arrays:")
print(x)
print(y)

# Create an element-wise comparison (greater) of two given arrays and print the result
print("Element-wise comparison (greater):")
print(np.greater(x, y))

# Create an element-wise comparison (greater_equal) of two given arrays and print the result
print("Element-wise comparison (greater_equal):")
print(np.greater_equal(x, y))

# Create an element-wise comparison (less) of two given arrays and print the result
print("Element-wise comparison (less):")
print(np.less(x, y))

# Create an element-wise comparison (less_equal) of two given arrays and print the result
print("Element-wise comparison (less_equal):")
print(np.less_equal(x, y))


Original arrays:
[1 2 3 4]
[1 2 3 5]
Element-wise comparison (greater):
[False False False False]
Element-wise comparison (greater_equal):
[ True  True  True False]
Element-wise comparison (less):
[False False False  True]
Element-wise comparison (less_equal):
[ True  True  True  True]


11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [1]:
# 11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

# Create two NumPy arrays 'x' and 'y'
x = np.array([1, 2, 3, 4])
y = np.array([1.0001, 2.0002, 3.0003, 4.0004])

# Print the original arrays
print("Original arrays:")
print(x)
print(y)

# Create an element-wise comparison (equal) of two given arrays and print the result
print("Element-wise comparison (equal):")
print(np.equal(x, y))

# Create an element-wise comparison (equal within a tolerance) of two given arrays and print the result
print("Element-wise comparison (equal within a tolerance):")
print(np.isclose(x, y, atol=0.0005))



NameError: name 'np' is not defined

12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [2]:
#12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

import numpy as np

# Create an array with the values 1, 7, 13, 105
arr = np.array([1, 7, 13, 105])

# Print the array
print(arr)

# Determine the size of the memory occupied by the array
size_bytes = arr.nbytes
size_kilobytes = size_bytes / 1024
size_megabytes = size_kilobytes / 1024

# Print the size of the memory occupied by the array in bytes, kilobytes, and megabytes
print(f"Size of the array in bytes: {size_bytes}")
print(f"Size of the array in kilobytes: {size_kilobytes}")
print(f"Size of the array in megabytes: {size_megabytes}")


[  1   7  13 105]
Size of the array in bytes: 32
Size of the array in kilobytes: 0.03125
Size of the array in megabytes: 3.0517578125e-05


13. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives.

In [3]:
#13. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives.

# Create an array of 10 zeros
zeros = np.zeros(10)

# Create an array of 10 ones
ones = np.ones(10)

# Create an array of 10 fives
fives = np.full(10, 5)

# Combine the arrays
combined_array = np.concatenate((zeros, ones, fives))

# Print the combined array
print(combined_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


14. Write a NumPy program to create an array of integers from 30 to 70.


In [4]:
#14. Write a NumPy program to create an array of integers from 30 to 70.

import numpy as np

# Create an array of integers from 30 to 70
arr = np.arange(30, 71)

# Print the array
print(arr)


[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


15.Write a NumPy program to create an array of all even integers from 30 to 70.

In [5]:
#  15.Write a NumPy program to create an array of all even integers from 30 to 70.

# Create an array of all even integers from 30 to 70
even_arr = np.arange(30, 71, 2)

# Print the array
print(even_arr)


[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


16. Write a NumPy program to create a 3x3 identity matrix.


In [7]:
# 16. Write a NumPy program to create a 3x3 identity matrix.

# Import the NumPy library
import numpy as np

# Create a 3x3 identity matrix
identity_matrix1 = np.eye(3)
identity_matrix2 = np.identity(3)

# Print the identity matrix
print(identity_matrix1)
print(identity_matrix2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


17. Write a NumPy program to generate a random number between 0 and 1.

In [8]:
# 17. Write a NumPy program to generate a random number between 0 and 1.

import numpy as np

# Generate a random number between 0 and 1
random_number = np.random.rand(1)

# Print the random number
print(random_number)


[0.23551119]


18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [9]:
# 18.Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

# Import the NumPy library
import numpy as np

# Generate an array of 15 random numbers from a standard normal distribution
random_numbers = np.random.randn(15) #or np.random.normal(0, 1, 15)

# Print the array
print(random_numbers)


[-0.98889713 -0.37625264 -0.10414217  0.88602277  0.74436146 -0.27831449
 -0.12398265 -0.82700432 -0.86480662  0.73832657  1.11392878  0.8785762
 -0.50654496  0.19367525 -0.27992645]


19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [10]:
#19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

import numpy as np

# Create a vector with values ranging from 15 to 55
vector = np.arange(15, 56)

# Print all values except the first and last
print(vector[1:-1])


[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


20. Write a NumPy program to create a 3X4 array and iterate over it.

In [11]:
# 20. Write a NumPy program to create a 3X4 array and iterate over it.

import numpy as np

# Create a 3x4 array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Iterate over the array using a for loop
for row in arr:
  for col in row:
    print(col)


1
2
3
4
5
6
7
8
9
10
11
12


21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [12]:
# 21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

import numpy as np

# Create a vector of length 10 with values evenly distributed between 5 and 50
vector = np.linspace(5, 50, 10)

# Print the vector
print(vector)


[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [13]:
#22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

import numpy as np

# Create a vector with values from 0 to 20
vector = np.arange(0, 21)

# Change the sign of the numbers in the range from 9 to 15
vector[9:16] *= -1

# Print the vector
print(vector)


[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


23. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.


In [14]:
# prompt: 23. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

import numpy as np

# Create a vector of length 5 filled with arbitrary integers from 0 to 10
vector = np.random.randint(0, 11, size=5)

# Print the vector
print(vector)


[2 9 9 6 9]


24. Write a NumPy program to multiply the values of two given vectors.

In [15]:
# 24. Write a NumPy program to multiply the values of two given vectors.

import numpy as np

# Create two vectors
vector1 = np.array([1, 2, 3, 4])
vector2 = np.array([5, 6, 7, 8])

# Multiply the values of two vectors
result = np.multiply(vector1, vector2)

# Print the result
print(result)


[ 5 12 21 32]


25. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [16]:
# prompt: 25. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

# Create a 3x4 matrix filled with values from 10 to 21
matrix = np.arange(10, 22).reshape(3, 4)

# Print the matrix
print(matrix)


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


26. Write a NumPy program to find the number of rows and columns in a given matrix.

In [18]:
# prompt: 26. Write a NumPy program to find the number of rows and columns in a given matrix.

import numpy as np

# Create a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Find the number of rows and columns in the matrix
rows, columns = matrix.shape

# Print the number of rows and columns
print("Number of rows:", rows)
print("Number of columns:", columns)


Number of rows: 3
Number of columns: 3


27. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0.

In [19]:
# prompt: 27. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0.

import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

# Print the identity matrix
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


28. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [22]:
# prompt: 28. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

import numpy as np

# Create a 10x10 matrix filled with zeros
matrix = np.zeros((10, 10))

# Set the elements on the borders to 1
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1

# Print the matrix
print(matrix)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


29. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [23]:
# prompt: 29. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

import numpy as np

# Create a 5x5 zero matrix
matrix = np.zeros((5, 5))

# Set the elements on the main diagonal to 1, 2, 3, 4, 5
np.fill_diagonal(matrix, range(1, 6))

# Print the matrix
print(matrix)


[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


30. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [26]:
# prompt: 30. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

import numpy as np

# Create a 4x4 matrix filled with zeros
matrix = np.zeros((4, 4))

# Set the elements in a staggered pattern
matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1

# Print the matrix

print(matrix)


[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [37]:
n=np.arange(1,17).reshape(4,4)
print(n)
n[::2, 1::2]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[ 2,  4],
       [10, 12]])

31. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

In [38]:
# prompt: 31. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

import numpy as np

# Create a 3x3x3 array filled with arbitrary values
array = np.random.rand(3, 3, 3)

# Print the array
print(array)


[[[0.73719466 0.67788955 0.79745171]
  [0.78398122 0.91845427 0.61486704]
  [0.86884215 0.57756609 0.55474803]]

 [[0.2696379  0.36245437 0.3254424 ]
  [0.89310656 0.15481563 0.29543513]
  [0.96877635 0.05770937 0.52403406]]

 [[0.06446062 0.03004322 0.43825152]
  [0.09032721 0.53145754 0.40950852]
  [0.6803741  0.86726718 0.56645733]]]


32. Write a NumPy program to compute the sum of all elements, the sum of each column and the sum of each row in a given array.

In [40]:
# prompt: 32. Write a NumPy program to compute the sum of all elements, the sum of each column and the sum of each row in a given array.

import numpy as np

# Create a random array
array = np.random.randint(1, 10, size=(3, 3))

# Compute the sum of all elements
sum_of_all_elements = np.sum(array)

# Compute the sum of each column
sum_of_columns = np.sum(array, axis=0)

# Compute the sum of each row
sum_of_rows = np.sum(array, axis=1)

# Print the results
print("Sum of all elements:", sum_of_all_elements)
print("Sum of each column:", sum_of_columns)
print("Sum of each row:", sum_of_rows)
sum_of_columns.sum()


Sum of all elements: 44
Sum of each column: [12 21 11]
Sum of each row: [16 13 15]


44

33. Write a NumPy program to compute the inner product of two given vectors.

In [41]:
# prompt: 33. Write a NumPy program to compute the inner product of two given vectors.

import numpy as np

# Define two vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Compute the inner product of two vectors
inner_product = np.dot(vector1, vector2)

# Print the inner product
print("Inner product of two vectors:", inner_product)


Inner product of two vectors: 32


34. Write a NumPy program to add a vector to each row of a given matrix.

In [43]:
# prompt: 34. Write a NumPy program to add a vector to each row of a given matrix.

import numpy as np

# Define a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Define a vector
vector = np.array([7, 8, 9])

# Add the vector to each row of the matrix
matrix_with_vector_added = matrix + vector

# Print the resulting matrix
print(matrix_with_vector_added)


[[ 8 10 12]
 [11 13 15]]
